test:
  adapter: postgresql
  database: num_test
  pool: 5
  host: localhost

development:
  adapter: postgresql
  encoding: unicode
  database: num_development
  pool: 5
  host: localhost

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 1 %>